version: "3.9"

services:
  client:
    container_name: my-todo-client
    build: ./client
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - server

  server:
    container_name: my-todo-server
    build: ./server
    ports:
      - 5000:5000
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: my-todo-db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 15s
        retries: 4
